on:
  workflow_dispatch:
  schedule:
    # run every day at 12 AM UTC
    - cron: "0 0 * * *"
name: Delete Workflow Runs
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Delete older workflows
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: false
          delete_workflows: true
          workflows_keep_day: 0
          gh_token: ${{ secrets.GITHUB_TOKEN }}
